# Generated by Django 4.2.3 on 2023-08-31 15:45

from django.db import migrations, models
import news.validation


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[news.validation.title_count_validation],
            ),
        ),
    ]
